package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.domain.model.DayStatus
import com.example.domain.model.WorkCalculationSummary
import com.example.ui.mvi.WorkUiState
import java.io.File
import java.io.FileOutputStream
import java.util.Locale

typealias UiState = WorkUiState

object ReportExportHelper {

    /**
     * Share plain text summary
     */
    fun shareTextSummary(context: Context, summary: WorkCalculationSummary, uiState: UiState) {
        val reportText = buildString {
            appendLine("📊 Work Timesheet Report - ${uiState.formattedReportMonthHeader}")
            appendLine("User: ${uiState.userName}")
            appendLine("────────────────────────────────────────")
            appendLine("⏱ Total Worked:     ${summary.formattedTotalWorked()}")
            appendLine("🎯 Target Required: ${summary.formattedRequiredTotal()} (${summary.formattedDailyTarget()}/day × ${summary.workingDaysCount} work days)")
            appendLine("🟢 Overtime:         ${summary.formattedOvertime()}")
            appendLine("🔴 Deficit:          ${summary.formattedDeficit()}")
            appendLine("⚖️ Net Balance:      ${summary.formattedNetBalance()}")
            appendLine("✅ Completed Days:   ${summary.completedDaysCount}/${uiState.totalDaysInReportMonth}")
            appendLine("🌴 Off Days:         ${summary.offDaysCount}")
            appendLine("💼 Working Days:     ${summary.workingDaysCount}")
            appendLine("────────────────────────────────────────")
            appendLine("Generated by Work Timesheet")
        }

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "Timesheet Report - ${uiState.formattedReportMonthHeader}")
            putExtra(Intent.EXTRA_TEXT, reportText)
        }
        context.startActivity(Intent.createChooser(intent, "Share Report via Text"))
    }

    /**
     * Share CSV / Excel compatible spreadsheet with daily breakdown and totals
     */
    fun shareCsvExcel(context: Context, summary: WorkCalculationSummary, uiState: UiState) {
        try {
            val reportsDir = File(context.cacheDir, "reports").apply { mkdirs() }
            val fileName = "Timesheet_${uiState.reportYear}_${uiState.reportMonth}.csv"
            val file = File(reportsDir, fileName)

            FileOutputStream(file).use { out ->
                // UTF-8 BOM for Microsoft Excel compatibility with special characters/Persian
                out.write(byteArrayOf(0xEF.toByte(), 0xBB.toByte(), 0xBF.toByte()))

                val writer = out.bufferedWriter(Charsets.UTF_8)
                writer.write("Work Timesheet Report,${uiState.formattedReportMonthHeader}\n")
                writer.write("Employee Name,${uiState.userName}\n")
                writer.write("Total Worked,${summary.formattedTotalWorked()}\n")
                writer.write("Target Required,${summary.formattedRequiredTotal()}\n")
                writer.write("Overtime,${summary.formattedOvertime()}\n")
                writer.write("Deficit,${summary.formattedDeficit()}\n")
                writer.write("Net Balance,${summary.formattedNetBalance()}\n")
                writer.write("Completed Days,${summary.completedDaysCount}\n")
                writer.write("Off Days,${summary.offDaysCount}\n\n")

                // Table Header
                writer.write("Day,Date,Enter,Exit,Worked,Target,Diff,Status,Notes\n")

                summary.daySummaries.forEach { item ->
                    val dayNum = item.day.dayNumber
                    val dateFormatted = "${uiState.reportYear}/${uiState.reportMonth.toString().padStart(2, '0')}/${dayNum.toString().padStart(2, '0')}"
                    val enter = item.day.formattedEnterTime()
                    val exit = item.day.formattedExitTime()
                    val worked = WorkCalculationSummary.formatMinutes(item.workedMinutes)
                    val target = WorkCalculationSummary.formatMinutes(item.targetMinutes)
                    val diff = WorkCalculationSummary.formatMinutes(kotlin.math.abs(item.diffMinutes))
                    val diffWithSign = if (item.diffMinutes > 0) "+$diff" else if (item.diffMinutes < 0) "-$diff" else diff

                    val status = when (item.status) {
                        DayStatus.DAY_OFF -> "Day Off"
                        DayStatus.OVERTIME -> "Overtime"
                        DayStatus.DEFICIT -> "Deficit"
                        DayStatus.EXACT -> "Met Target"
                        DayStatus.IN_PROGRESS -> "In Progress"
                        DayStatus.UNSET -> "Not Logged"
                    }
                    val notes = item.day.note.replace(",", " ")

                    writer.write("$dayNum,$dateFormatted,$enter,$exit,$worked,$target,$diffWithSign,$status,\"$notes\"\n")
                }

                writer.flush()
            }

            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/comma-separated-values"
                putExtra(Intent.EXTRA_SUBJECT, "Timesheet CSV/Excel - ${uiState.formattedReportMonthHeader}")
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(intent, "Share Excel/CSV Report"))
        } catch (e: Exception) {
            Toast.makeText(context, "Error generating CSV: ${e.localizedMessage}", Toast.LENGTH_SHORT).show()
        }
    }

    /**
     * Generate high-quality native PDF Report and share
     */
    fun sharePdfReport(context: Context, summary: WorkCalculationSummary, uiState: UiState) {
        try {
            val pdfDoc = PdfDocument()
            val pageWidth = 595 // A4 standard width in points at 72dpi
            val pageHeight = 842 // A4 standard height
            val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
            val page = pdfDoc.startPage(pageInfo)
            val canvas = page.canvas

            val paint = Paint().apply { isAntiAlias = true }

            // Header Background
            paint.color = Color.parseColor("#1565C0") // Primary Blue
            canvas.drawRect(0f, 0f, pageWidth.toFloat(), 95f, paint)

            // Header Text
            paint.color = Color.WHITE
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            paint.textSize = 20f
            canvas.drawText("Monthly Work Timesheet Report", 28f, 40f, paint)

            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            paint.textSize = 13f
            canvas.drawText("Month: ${uiState.formattedReportMonthHeader}    |    User: ${uiState.userName}", 28f, 68f, paint)

            // Summary Stats Cards Banner
            var yPos = 118f
            paint.color = Color.parseColor("#F1F5F9")
            canvas.drawRoundRect(24f, yPos, (pageWidth - 24).toFloat(), yPos + 60f, 8f, 8f, paint)

            val colW = (pageWidth - 48f) / 4f
            val cardTitles = listOf("Total Worked", "Target Required", "Overtime", "Deficit")
            val cardValues = listOf(
                summary.formattedTotalWorked(),
                summary.formattedRequiredTotal(),
                summary.formattedOvertime(),
                summary.formattedDeficit()
            )
            val cardColors = listOf(
                Color.parseColor("#1565C0"),
                Color.parseColor("#475569"),
                Color.parseColor("#16A34A"),
                Color.parseColor("#DC2626")
            )

            for (i in 0..3) {
                val cx = 24f + (i * colW) + 12f
                paint.color = Color.parseColor("#64748B")
                paint.textSize = 9.5f
                paint.typeface = Typeface.DEFAULT
                canvas.drawText(cardTitles[i], cx, yPos + 22f, paint)

                paint.color = cardColors[i]
                paint.textSize = 13f
                paint.typeface = Typeface.DEFAULT_BOLD
                canvas.drawText(cardValues[i], cx, yPos + 46f, paint)
            }

            yPos += 78f

            // Table Header
            paint.color = Color.parseColor("#2563EB")
            canvas.drawRect(24f, yPos, (pageWidth - 24).toFloat(), yPos + 24f, paint)

            paint.color = Color.WHITE
            paint.textSize = 9.5f
            paint.typeface = Typeface.DEFAULT_BOLD

            val headers = listOf("Day", "Enter", "Exit", "Worked", "Target", "Diff", "Status")
            val colPositions = floatArrayOf(30f, 75f, 135f, 195f, 265f, 335f, 410f)

            headers.forEachIndexed { i, title ->
                canvas.drawText(title, colPositions[i], yPos + 16f, paint)
            }

            yPos += 24f

            // Table Rows
            paint.textSize = 8.5f
            val rowHeight = 17.5f

            summary.daySummaries.forEachIndexed { index, item ->
                if (yPos + rowHeight > pageHeight - 40f) return@forEachIndexed

                // Zebra striping
                paint.color = if (index % 2 == 0) Color.parseColor("#F8FAFC") else Color.WHITE
                canvas.drawRect(24f, yPos, (pageWidth - 24).toFloat(), yPos + rowHeight, paint)

                // Row text
                paint.typeface = Typeface.DEFAULT
                paint.color = Color.parseColor("#1E293B")

                val diffAbs = WorkCalculationSummary.formatMinutes(kotlin.math.abs(item.diffMinutes))
                val diffFormatted = if (item.diffMinutes > 0) "+$diffAbs" else if (item.diffMinutes < 0) "-$diffAbs" else diffAbs

                val statusText = when (item.status) {
                    DayStatus.DAY_OFF -> "Day Off"
                    DayStatus.OVERTIME -> "Overtime"
                    DayStatus.DEFICIT -> "Deficit"
                    DayStatus.EXACT -> "Exact"
                    DayStatus.IN_PROGRESS -> "In Progress"
                    DayStatus.UNSET -> "-"
                }

                val statusColor = when (item.status) {
                    DayStatus.DAY_OFF -> Color.parseColor("#2563EB")
                    DayStatus.OVERTIME -> Color.parseColor("#16A34A")
                    DayStatus.DEFICIT -> Color.parseColor("#DC2626")
                    DayStatus.EXACT -> Color.parseColor("#475569")
                    DayStatus.IN_PROGRESS -> Color.parseColor("#D97706")
                    DayStatus.UNSET -> Color.parseColor("#94A3B8")
                }

                val workedText = if (item.workedMinutes > 0) WorkCalculationSummary.formatMinutes(item.workedMinutes) else "-"
                val targetText = if (item.targetMinutes > 0) WorkCalculationSummary.formatMinutes(item.targetMinutes) else "-"

                canvas.drawText("${item.day.dayNumber}", colPositions[0], yPos + 12f, paint)
                canvas.drawText(item.day.formattedEnterTime(), colPositions[1], yPos + 12f, paint)
                canvas.drawText(item.day.formattedExitTime(), colPositions[2], yPos + 12f, paint)
                canvas.drawText(workedText, colPositions[3], yPos + 12f, paint)
                canvas.drawText(targetText, colPositions[4], yPos + 12f, paint)
                canvas.drawText(diffFormatted, colPositions[5], yPos + 12f, paint)

                paint.color = statusColor
                paint.typeface = Typeface.DEFAULT_BOLD
                canvas.drawText(statusText, colPositions[6], yPos + 12f, paint)

                yPos += rowHeight
            }

            // Footer
            paint.color = Color.parseColor("#94A3B8")
            paint.textSize = 8.5f
            paint.typeface = Typeface.DEFAULT
            canvas.drawText("Generated by Work Timesheet App  •  ${uiState.formattedReportMonthHeader}", 28f, (pageHeight - 20).toFloat(), paint)

            pdfDoc.finishPage(page)

            val reportsDir = File(context.cacheDir, "reports").apply { mkdirs() }
            val pdfFile = File(reportsDir, "Timesheet_${uiState.reportYear}_${uiState.reportMonth}.pdf")
            FileOutputStream(pdfFile).use { out ->
                pdfDoc.writeTo(out)
            }
            pdfDoc.close()

            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                pdfFile
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_SUBJECT, "Timesheet PDF Report - ${uiState.formattedReportMonthHeader}")
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(intent, "Share PDF Report"))
        } catch (e: Exception) {
            Toast.makeText(context, "Error generating PDF: ${e.localizedMessage}", Toast.LENGTH_SHORT).show()
        }
    }
}
